---
title: "¿Cómo se distribuye la precariedad laboral en Chile? Una propuesta tipológica para analizar las condiciones de trabajo del sector servicios durante la pandemia"
author: Emilia Barrientos, Pablo Campos, NicolÃƒÂ¡s Godoy, Monserrat Greene y Gonzalo
  LÃƒÂ³pez
date: "04-10-2021"
output:
  pdf_document:
    toc: yes
  html_document:
    highlight: textmate
    theme: paper
    toc: yes
bibliography: ciencia_abierta.bib
csl: apa_csl
---
```{r}
install.packages("citr")

```

#Resumen

Las reformas asociadas al Plan Laboral de 1979 significaron un cambio en la estructura del trabajo, derivando con frecuencia en relaciones precarias e inestables para trabajadores y trabajadoras, en ámbitos como seguridad laboral, estabilidad contractual y certidumbre. Durante el período postpinochetista, la institucionalidad laboral se ha mantenido inmutable en sus aspectos fundamentales. Junto a esto, la aparición de la actual crisis sanitaria provocada por el COVID-19 ha sido un factor crítico en las dinámicas del mercado laboral, aumentando el riesgo de contagio y/o despido para quienes trabajan, o el deterioro en la calidad de los empleos. Dado ese contexto, se busca abordar la problemática de la precariedad laboral y la distribución de sus patrones en trabajadoras y trabajadores subcontratados en el año 2020 en Chile. Para ello, se utilizaron los datos de la Encuesta Suplementaria de Ingresos (ESI) en su versión 2020, filtrando aquellos datos que refieren a trabajadores y trabajadoras del sector servicios (N = 3.756), para modelar un análisis de clases latentes que recogerá las multidimensionalidad de la precariedad laboral - siguiendo la operacionalización de Blanco y Julián (2019) -, incluyendo (in)estabilidad, (in)seguridad, (in)suficiencia, condiciones de trabajo y cronopiedad. A partir del análisis se seleccionó el modelo de 4 clases, ...
El contraste realizado a partir del cruce por las variables *sexo*, *edad* y *nivel educacional* arrojó que...




#Introducción

Actualmente, el mundo se ve imbricado en un proceso particular que incrementa aspectos como la inseguridad, la incertidumbre y riesgos en el área de la salud. Sin embargo, el COVID-19 no solo ha afectado la situación económica y sanitaria, sino que ha incidido fuertemente en el área laboral. Esa incidencia no solo refiere al desempleo creciente que se ha evidenciado en Chile, sino que también a los riesgos que conlleva el efectuar actividades laborales presenciales en una crisis sanitaria como ésta, perjudicando a sectores más informales del mercado laboral (Marchetti, 2020). Este proceso, en palabras de Butler, ha evidenciado los límites del capitalismo y la centralidad que posee el mercado en la vida social, ante esto la autora pone énfasis en la reformulación del rol que cumple el Estado en el capitalismo actual (Citado en Boccardo, 2020). 

En Chile, el mundo laboral ha sido marcado por las modernizaciones que trajo consigo la dictadura militar (1973-1990), que implicó una reestructuración económica consolidada como proyecto económico, social y cultural (Pérez, 2019). Así, la precariedad laboral se vió amplificada en un contexto en el que el Estado no es garante de derechos, dado su carácter neoliberal (Lázaro & Jubany, 2017). La flexiprecariedad como fenómeno resume la inestabilidad laboral ligada a las normativas económicas capitalistas implementadas en Chile. Es decir, corresponde a una característica central en el proceso de producción capitalista y es un mecanismo que conlleva consecuencias directas en detrimento de las personas trabajadoras del país (Aguiar, 2010). 

Tomando en cuenta estos antecedentes, es menester considerar la calidad laboral como un fenómeno multidimensional, donde no solo las remuneraciones son decisivas, sino también las relaciones contractuales, las oportunidades de trabajo, la calidad del empleo, entre otros (Anxo et al., 2017). Por ello, es necesario dar cuenta del proceso más general dentro del cual se hace presente la subcontratación: la externalización. De acuerdo con lo planteado por Echeverría (2006), el proceso externalizador de la producción y del trabajo se entiende como una de las características de la economía globalizada, ampliamente desarrollada en América Latina desde los años ochenta. En Chile, específicamente, este proceso ha alcanzado presencia y se ha instalado bajo distintas modalidades (González, 2014). Pese a esto, es importante resaltar que la subcontratación como régimen laboral no implica necesariamente precariedad en su sentido estricto. Esto porque, dependiendo de factores como los ya mencionados por Anxo et al. (2017) y específicamente de la mano de las relaciones contractuales, el trabajo subcontratado puede verse propenso a riesgos, precariedad e inestabilidad cuando dicha relación se posiciona en un espacio desregulado; pero también puede representar estabilidad y buenas condiciones laborales cuando la relación entre empleador y trabajador es definida y regulada de forma clara (Echeverría, 2006).

En tal sentido, continuando con lo expuesto por Echeverría (2006) se erigen dos lineamientos en torno a la subcontratación; uno positivo relacionado con la idea de modernidad económica y otro negativo donde aparecen las características propias de este tipo de régimen: precarización, incertidumbre, desarticulación organizacional, problemas en la sindicalización, entre otros.

Para efectos del presente trabajo de investigación, se entenderá a la subcontratación bajo el segundo lineamiento, poniendo especial énfasis en el análisis de las condiciones laborales en el contexto de la subcontratación en el sector servicios. Este sector económico, caracterizado por una mayor distribución y concentración de mujeres (MINTRAB, 2019), puede concentrar a su vez, las condiciones de empleo más precarizadas, debido a los patrones asociados en la fuerza de trabajo, lo que da pie a niveles o posiciones que oscilan entre la precarización y otras no precarias.
 
A nivel global, estos patrones masculinos y femeninos de participación en la fuerza de trabajo han entrado en convergencia, siendo los tipos de empleo tradicionalmente relacionados a las mujeres -de baja remuneración, inestables, inseguros, desprotegidos-, ampliados a tipos de empleo asociados a hombres -estables, sindicalizados, regulares (Standing, 1999).
 
Así, Antunes (2005) señala el aumento considerable del trabajo femenino dentro de la clase trabajadora, especialmente en formas de trabajo “precarizado, subcontratado, tercerizado, a tiempo parcial” (p. 185) como una importante consecuencia de las transformaciones en el proceso de producción. Por ello, se puede relacionar la composición feminizada del sector a condiciones laborales precarias; sin embargo, el presente trabajo, también incluirá hombres para evidenciar posibles diferencias en las condiciones laborales en función del sexo. 

En añadidura, este sector de la economía resulta complejo de definir ya que los cambios tecnológicos de la última década han diversificado aún más las actividades de servicios (Weller, 2001). Pese a esto, existe consenso en establecer que dicho sector guarda una clara heterogeneidad en su composición (Weller, 2001; Ravest, 2016), ya sea desde una mirada a las actividades productivas, como desde una mirada a variables más clasificatorias de la población (sexo, nivel educativo, edad). En adición, puede entenderse que “la producción terciaria es definida por residual como consistiendo en todas las demás actividades económicas, las principales de las cuales son: transporte, distribución, administración pública, servicio doméstico y todas las demás actividades cuyo producto es de una naturaleza no-material” (Guadagni, 1964, p.187). 

No obstante, Weller (2001) plantea que las características propias de las actividades terciarias lo constituyen como un sector dinámico y cambiante a lo largo del tiempo. En tal sentido, el autor recomienda que la mejor manera de diferenciar dichas actividades va a depender de la interrogante que siga cada investigación. Sin embargo, existen ciertas ocupaciones del sector servicios de carácter notablemente feminizado, tales como la educación, salud y servicios de aseo (Schönhaut, 2020). Al respecto Semenza et al. (2020) sostienen que pese al incremento en la participación de las mujeres en todos los sectores de las actividades terciarias, ellas se encuentran mayoritariamente concentradas “en servicios de baja calificación o, si son altamente calificadas, se emplean principalmente en ocupaciones vinculadas a los sectores de la salud o la educación” (p. 10). Además, en dicho estudio se evidencia que las mujeres se concentran en sólo dos sectores a saber, educación, salud humana, otros servicios y administración pública, mientras que se encuentran subrepresentadas en lo que es entendido en el estudio como sector terciario avanzado. De esta manera, en la realidad chilena pueden reconocerse múltiples ocupaciones donde prima la mano de obra femenina, expuesta en mayor o menor grado a condiciones de precarización laboral.

Para sintetizar; en primer lugar, la subcontratación en el sector servicios en un contexto sanitario como el COVID- 19 constituye una temática que debe ser profundizada mediante nuevas investigaciones para ampliar el conocimiento de las dinámicas y consecuencias de la pandemia sobre la estructura del mercado laboral. En segundo lugar, la desprotección laboral mediante mecanismos flexibilizadores puede incrementar perjuicios hacia las y los trabajadores, tanto a nivel individual (mediante factores salubres, previsionales o psicológicos) como colectivo (mediante una carencia organizativa y representativa de sus intereses), siendo relevante la tarea de poner evidencia las consecuencias de estos mecanismos precarizantes para contribuir a su erradicación. En tercer lugar, estas dinámicas de precariedad laboral se ven incrementadas por un proceso mundial y sanitario que aumenta los riesgos laborales e incertidumbres provocadas por mecanismos flexibilizadores e individualizantes, como la subcontratación (Boccardo, 2020). Finalmente, al evidenciar estos mecanismos flexibilizadores del trabajo, potenciados por el contexto sanitario, se puede contribuir al conocimiento de un sector menos estudiado, reconocer sus carencias en el ámbito laboral y, así, contribuir con un insumo para la futura generación de políticas que permitan paliar las carencias de este sector.

Ante esto, la pregunta que guiará el desarrollo de la presente investigación es: 

¿Cuáles son las diferencias en los tipos de precariedad laboral de trabajadoras y trabajadores subcontratados en el sector servicios, entre el trimestre de mayo-julio del 2019 y el mismo trimestre del 2020, en Chile?

Así, el objetivo principal será caracterizar los diferentes tipos de precariedad laboral de trabajadoras y trabajadores subcontratados del sector servicios en el trimestre de mayo-julio del año 2019 y 2020 en Chile.

Para el cumplimiento de este fin, los objetivos específicos consistirán en realizar un análisis de la estructura de las condiciones precarias de las y los trabajadores del sector servicios mediante un análisis de clases latentes para los trimestres mayo-julio del 2019 y del 2020; para luego llevar a cabo un análisis descriptivo de las trabajadoras y trabajadores subcontratados del sector servicios en el trimestre mayo-julio del año 2019 y 2020 en Chile; finalmente, caracterizar la configuración subjetiva de los tipos de precariedad  en la experiencia de las y los trabajadores del sector servicios en el trimestre mayo-julio del año 2019 y 2020 en Chile.

El objeto de estudio de la presente investigación se justifica dado que la subcontratación es por excelencia el método de externalización utilizado en Chile (Echeverría, 2010). Este proceso se caracteriza por brindarle mayores capacidades y facilidades al empleador,  así como menores seguridades y condiciones laborales al trabajador, implicando un ahorro en los costos productivos en pos de los contratistas, generando trabajadores precarizados en el mercado laboral (Ramos, 2009). De ahí en más, resulta interesante estudiar esta tendencia de la mano de la subcontratación y sus consecuentes precariedades, incorporando la crisis sanitaria al análisis y centrando la mirada en las y los trabajadores del sector servicios.

Así, el punto neurálgico al que apunta este trabajo investigativo es la precariedad laboral del sector servicios subcontratado. La fisionomía del sector servicios chileno ya ha sido investigada previamente desde una óptica cuantitativa por Ravest (2016), confirmando su elevada heterogeneidad a partir de un análisis de conglomerados, que permitió identificar cuatro tipos de trabajadores de servicios.  En concreto, un antecedente clave que se rescata de tal investigación es que las mujeres y las personas de mayor edad del sector servicios serían las que tendrían condiciones laborales y de protección social de mayor cercanía a rangos de vulnerabilidad (Ravest, 2016). 
Ahora bien, el estudio propuesto se diferencia en su método mixto de análisis, que integra un análisis descriptivo y un análisis de clases latentes, que serán luego profundizadas mediante análisis documental de datos secundarios. Se busca que esta investigación no sea únicamente una caracterización a nivel estadístico, por lo que se pretende complementar con técnicas cualitativas que permitan ahondar en las subjetividades contenidas en la tipología identificada. Se espera que la combinación de estas técnicas entregue un panorama general que pueda cristalizar de manera más completa este vigente y relevante fenómeno. 
La temporalidad escogida en la presente investigación no es azarosa, ya que los trimestres seleccionados en el año 2020 se han identificado como uno de los trimestres con mayor alza en los contagios diarios, y con mayor concentración de comunas en cuarentena (Villarroel, 2020).  En ese sentido, resulta interesante hacer una investigación comparativa que incluya un período previo a la pandemia y uno durante ella. Abordar de manera comparativa ambas temporalidades permitirá ahondar en la pregunta acerca de la incidencia de la pandemia en las formas precariedad laboral. 
Los procesos de subcontratación laboral y feminización de la mano de obra se configuran como transformaciones que llevan varias décadas desarrollándose y que ya han sido estudiadas.  En ese sentido, Standing (1999) señala que la feminización y la flexibilización del trabajo son tendencias que avanzan desde hace décadas hacia una mayor inseguridad y desigualdad en el ámbito laboral, por lo que revertir esta tendencia implica un desafío sustancial. Así, en el presente trabajo, la subcontratación será comprendida como forma de flexibilidad, donde su imbricación con la feminización genera mecanismos de precarización.

Por ello, el estudio propuesto busca nutrir de discusión al debate actual al interior de la disciplina al articular y problematizar la crisis sanitaria, el proceso de subcontratación en un sector económico laboral feminizado como el de servicios; esfuerzos que, además, pueden dar pie a futuras investigaciones. Así, esta investigación pretende evidenciar cómo se ha comportado este fenómeno de manera específica en el contexto de pandemia, lo que significa un aporte al diagnóstico de la situación de trabajadores y trabajadoras del sector servicios. 

En adición, otro factor de importancia que puede guardar este estudio remite a su valor público, en tanto centra su foco de análisis en un fenómeno profundamente contingente como es el carácter de la precarización laboral de trabajadores y trabajadoras subcontratadas en el sector servicios, que hacen frente a las mutaciones del mercado laboral en una situación de desprotección y en medio de una extensa crisis sociosanitaria. 

El aporte de la presente investigación puede representar un valioso proceso para evidenciar los mecanismos de precarización que resultan, como fin último, en la optimización de recursos para empleadores. Al evidenciarse esta situación, estas prácticas se pueden someter tanto a un análisis activo, que permite comprenderlo de manera más cabal, como la propuesta de alternativas que permitan que procesos como la precarización laboral puedan ser mitigados con herramientas desarrolladas por medio de la teoría social. En este sentido, un estudio de este tipo puede guardar un gran valor empírico.



#Antecedentes

#Metodología

#Análisis

#Conclusión
